### ISSUE TITLE
fasttext module not found

### ISSUE THREAD

**Issue by kartikm** [digitalTranshumant/templatesAlignment#4]
In 03ProduceAlignments.ipynb,

`import fastText`

will lead error 'fastText module not found.

Installing fasttext as per https://fasttext.cc/docs/en/python-module.html requires changing `fastText` to `fasttext` in `fasttext.load_model` also.

**Comment by digitalTranshumant** [comment]
!pip install fasttext should do the work.

**Comment by kartikm** [comment]
Should we update requirements.txt for the latest version too?

**Comment by digitalTranshumant** [comment]
Yes

**Comment by kartikm** [comment]
Submitted: https://github.com/digitalTranshumant/templatesAlignment/pull/6
